<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>1.1.0</Version>
    <Company>NTY MULTIMEDIA CO.,LTD</Company>
    <Product>Classroom Control System</Product>
    <Copyright>Copyright © NTY MULTIMEDIA CO.,LTD</Copyright>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
